### ISSUE TITLE
Breakout CreateForm.test.jsx

### ISSUE THREAD

**Issue by pippinlee** [k88hudson/react-formation#35]
`tests/CreateForm.test.jsx` can likely be broken into further test files. One simple way to break them out would be to create a test file for each method included in `src/lib/apiDocs/`. So we'd have a test file for each of the following:
- didSubmit
- linkField
- submitForm
- submitGroup
- validateField

These describe blocks aren't specifically part of our api methods, so we could keep them in a single `CreateForm.test.jsx` file
- getSchema
- getValues

Does this make any sense?

**Comment by k88hudson** [comment]
yep!
